### ISSUE TITLE
Displaying document devtools is broken

### ISSUE THREAD

**Issue by iffy** [iffy/lhtml#32]
```
Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
    at toggleDocumentDevTools (/Users/matt/m/lhtml/dist/mac/LHTML.app/Contents/Resources/app.asar/main.js:598:20)
    at click (/Users/matt/m/lhtml/dist/mac/LHTML.app/Contents/Resources/app.asar/main.js:117:9)
    at MenuItem.click (/Users/matt/m/lhtml/dist/mac/LHTML.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/Users/matt/m/lhtml/dist/mac/LHTML.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15)
```

**Comment by iffy** [comment]
This happens when you are focused on the main window devtools.

**Comment by iffy** [comment]
Though sometimes the devtools don't open when even when you are focused on the right thing.
